[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
agent_payment_vault = "x402VauLt1111111111111111111111111111111111"

[programs.mainnet]
agent_payment_vault = "x402VauLt1111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
